- name: variable 
  hosts: localhost
  var:
    var.yaml
  tasks:
    - name: create the variables
      ansible.builtin.debug:
        msg: "hi I am doing {{job}}, Comapny name is {{Comapny}}"


    