- name: variables from PLAY level 
  hosts: localhost
  vars_files:
    - var.yaml
  tasks:
    - name: create the variables
      ansible.builtin.debug:
        msg: "hi I am doing {{job}}, Comapny name is {{Comapny}}"


    